Payment
1Kabman1/antifraud-payment-system pull request #2
Opened 2024-02-26 18:45 UTC by 1Kabman1

Ринат привет просьба проверить ))

[Added testins](https://github.com/1Kabman1/antifraud-payment-system/commit/3e15c467f2f3c8b7f6c9c8883835b037db903680)

2024-02-26 19:04 UTC, ribatulin commented on internal/services/handlers.go
>  			if aRule.AggregateValue == "amount" {
aRule.AggregateType (тип агрегата) + Enum  для возможных значений  "amount"/"count"

если писать строки хардкодом, а не использовать константы или Enum вместо строк, там где это логично, то это анти-паттерн - "магические строки", еще бывает "магические числа".

2024-02-26 20:04 UTC, ribatulin requested changes

2024-02-26 20:04 UTC, ribatulin commented on internal/transport/rest/handler.go
>  	r.Use(middleware.Logger)
логика именования разъехалась и вышла путаница на пустом месте.

Методы хендлера запросов, которые обрабатывают запросы должны называться созвучно роутам/путям, чтобы их легко было можно найти или понять из кода. 

1) r.Post(CreateRule, h.CreateAggregationRule) -> норм, правильно
2) r.Get(GetRule, h.AggregationData) -> а тут неверное название. Во первых /aggregation_rules/get значит метод и константу логично назвать h.GetAggregationRules , потому что мы при его вызове поулчаем информацию о созданных правилах
3) r.Post(registerOperation, h.CalculateTheAggregated) -> почему стал  h.CalculateTheAggregated ? так и оставил бы, ведь по смыслу это метод регистрации операции, а то что он внутри какие то агрегаты собирает, не должно быт отражено в названии. Мыслим асбтрактно от целей приложения, а не от его внутрянки. Ведь метод может к примеру этот не считать агрегаты, а писать их в БД тупо, а обсчет будет другой прогарммой выполняться. Но от этого он не перестанет быть методом регистрации операций. А отражать в названии надо суть, которая должна быть ясна для отго слоя, котрый будет вызывать метод. Не все детали реализации надо выносить в названиии метода.  Чтобы при смене реализации его не пришлось переименовывать.

2024-02-26 20:04 UTC, ribatulin commented on internal/services/handlers.go
> +func (h *Handlers) ToEstablishStorage() {
а если кроме Storage будем еще и другие свойства инициализировать, то метод будем переименовывать ?
это похоже на конструктор для Handlers, потому через New функцию , как сделано для Counter структуры, надо сделать просто. Ну и почему Handlers, когда просто Handlers (он же один хендлер, единственное число без s на конце, можно даже переименовать в ApiHandler, чтоб было ясно, что это хендлер запросов нашей апишки)

2024-02-26 20:04 UTC, ribatulin commented on internal/services/handlers.go
в mapPING смущает PING боьлшими буквами, смысла нет, а путаница есть, тк ping это тип сетевого запроса в протоколе ICMP и соответствующая утилита для осуществления пинга, зачем выделять PING в слово, сделай проссто mapping название

2024-02-26 20:04 UTC, ribatulin commented on internal/services/handlers.go
> +				c.Value += int(mapPING["amount"].(float64))
int, суммы всегда в копейках, дробных не бывает

2024-02-26 20:04 UTC, ribatulin commented on internal/services/services.go
> +		var flag bool
почему первый аргумент prepareTheDataForHashing называется h, а не Rules ? ведь там явно правила. 

второй аргумент для этой функции это уже operationProperties, свойства операции, а не mapping непонятный

2024-02-26 20:04 UTC, ribatulin commented on internal/services/services.go
> +					intInterface := int(aInterface)
float нет, одни инты в суммах, часть копейки прислать не можем

2024-02-26 20:04 UTC, ribatulin commented on internal/services/services.go
>  			} else { // Если хотябы одно агрегируемое из правила не совпадает с поступившим на почет поручением, то оно автоматом исключается
послезно не делать else в коде лишний раз и не множить вложенность блоков.
ведь можно сначала проверить

```
if (v=nil) {
flag = false
break <- сразу ломаем цикл
}

а дальше уже обцчный код без скобок и вложенности, для успешного случая, котолрый сейчас идет через вложенность в  ok {
......
```

2024-02-26 20:04 UTC, ribatulin commented on internal/transport/rest/handler.go
> +	h.ToEstablishStorage()
а если кроме Storage будем еще и другие свойства инициализировать, то метод будем переименовывать ?
это похоже на конструктор для Handlers, потому через New функцию , как сделано для Counter структуры, надо сделать просто. Ну и почему Handlers, когда просто Handlers (он же один хендлер, единственное число без s на конце, можно даже переименовать в ApiHandler, чтоб было ясно, что это хендлер запросов нашей апишки)

2024-02-26 20:06 UTC, ribatulin commented
Надо в README.md добавить блок-инструкцию по сборке, запуску, тестам программы 
с примерами команд консоли, которые позволяют собрать приложение, запустить его, и прогнать тесты

2024-02-27 06:22 UTC, 1Kabman1 commented on internal/services/handlers.go
> +func (h *Handlers) ToEstablishStorage() {
Переименовал Handlers в api Handler, удалил  метод ToEstablishStorage в место него реализовал конструктор для api Handler под названием NewApiHandler. Изменения затронули файлы aggregationData_test.go, calculateTheAggregated_test.go, handler.go, handler.go

2024-02-27 06:55 UTC, 1Kabman1 commented on internal/transport/rest/handler.go
>  	r.Use(middleware.Logger)
Переименовал Aggregation Data в GetAggregationRules. Также переименовал  Calculate The Aggregated в RegisterOperation чтобы выразить его суть а не внутреннюю реализацию.

2024-02-27 07:05 UTC, 1Kabman1 commented on internal/services/handlers.go
>  			if aRule.AggregateValue == "amount" {
Добавил const   для возможных значений "amount"/"count"

2024-02-27 07:08 UTC, 1Kabman1 commented on internal/services/handlers.go
Переименовал mapPING в mapping

2024-02-27 07:20 UTC, 1Kabman1 commented on internal/services/handlers.go
> +				c.Value += int(mapPING["amount"].(float64))
Данное выражение как раз  переводит тип  float64  в   int  - int(mapPING["amount"].(float64)) по другому бы не скомпелировался код. При мапинге json  определяет либой числовой тип в  float64. 
Я делаю мапинг для того чтобы уйти от поределенной структуры, как изначально и говорили абстрактно что программе должно быть все равно что считать.

2024-02-27 07:25 UTC, 1Kabman1 commented on internal/services/services.go
> +		var flag bool
В функции prepareTheDataForHashing изменил названия входящих аргументов h на  Rules и  mapPING на operationProperties

2024-02-27 07:29 UTC, 1Kabman1 commented on internal/services/services.go
> +					intInterface := int(aInterface)
Выражение int(aInterface) это как раз конвертация типа в int, на вход приходит только float64 это я так понимаю нюансы маппинга , json  определяет числовые значения исключительно  как float64

2024-02-27 07:35 UTC, 1Kabman1 commented on internal/services/services.go
>  			} else { // Если хотябы одно агрегируемое из правила не совпадает с поступившим на почет поручением, то оно автоматом исключается
В функции  prepareTheDataForHashing  во вложенном  цикле for  в ветке if  избавился от вспомогательной ветки else

2024-02-27 07:40 UTC, 1Kabman1 commented on internal/transport/rest/handler.go
> +	h.ToEstablishStorage()
убрал сделал "конструктор" 	h := services.NewApiHandler()

2024-02-28 09:22 UTC, ribatulin commented on api/.idea/.gitignore
удали папку .idea из git, а так же в корне проекта впиши в файле .gitignore  

./.idea/


и прочитай, для чего нужен gitignore и какой его формат, чтоб в проект левые файлы не влетали, которые унжны только у тебя на машине разработки

2024-02-28 09:24 UTC, ribatulin commented on internal/services/handler.go
> +	const (
этло надо вынести отдельно,  тк это типы агрегатов, их так же надо проверять на допустимость при создании правил, а значит там будет дубль этих значений? в идеале нужно вынести в Enum или что то типа того, вне хендлеров

2024-02-28 18:06 UTC, 1Kabman1 commented on api/.idea/.gitignore
Выполнено

2024-02-28 18:12 UTC, 1Kabman1 commented on internal/services/handler.go
> +	const (
Перенес в область глобальной видимости , в пределах пакета

2024-02-28 20:02 UTC, 1Kabman1 commented
Исправлено все по замечаниям

2024-03-02 18:53 UTC, ribatulin commented on .gitignore
> +.idea/workspace.xml
достаточно просто саму папку .idea/

2024-03-02 18:56 UTC, ribatulin commented on .gitignore
> +go.mod
gu sum и go.mod  по идее нельзя включать в гитигнор, они должны быть в гите закоммичены всегда, тк содержат версии зависимостей. 

если их не коммитить, то у другого человека при установке пакетов могут подтянуться другие версии пакетов (более новые и тд) и приложение может или не собрать, или собраться, но работать иначе, и проблему будет трудно отыскать, тк она в различных верисях зависимостей. поэтгому с кодом проекта всегда коммитим файлы, которые отвечают за версии зависимостей. почитай в гугле насчет того, надо ли класть эти файлы под управление git в репозиторий и расскажешь потом или просто сюда ответь

2024-03-02 18:58 UTC, ribatulin commented on internal/hashStorage/storage.go
> +		archivist: make(map[int]int),
что за архивист, неясное название и цель какая ?

2024-03-02 18:59 UTC, ribatulin commented on internal/hashStorage/storage.go
> +func (s *Storage) IsRule(key string) bool {
Is это обычно проверка на соответствие чему либо, а тут надо HasRule, так как будет проверка наличия

2024-03-02 18:59 UTC, ribatulin commented on internal/hashStorage/storage.go
> +func (s *Storage) IsCounter(key [16]byte) bool {
HasCounter скорее всего правильно назвать

2024-03-02 19:01 UTC, ribatulin commented on internal/hashStorage/storege_test.go
> +package hashStorage
в названии файла опечатка

2024-03-02 19:03 UTC, ribatulin commented on internal/services/handler.go
> +	if h.s.RulesLen() == 0 {
пустой массив отдавай, это не ошибка, что правил нет

2024-03-02 19:09 UTC, ribatulin commented on internal/services/handler.go
> +		w.Header().Set("Message", "rule already exists")
в заголовки не наод писать от, что должно бть в теле ответа. Заголовки это служебная мета информация к телу ответа. 

message и status всегда доолжны быть в  теле ответа, тк ты проектируешь API, принимающее на вход запросы, ну и отдавай нормальные ответы, а не названные самолично заголовки. Вообще заголовки просто так нельзя делать, тк их парсят браузеры и другие участники сетевого обмена, пользовательские заголовки в идеале делать начинающиеся с X-Создатель-Приложение-ИмяЗаголовка. Ну то есть X-Kabman-Antifraud-MyHeader

типа как неймспейс получается. и не будет конфликта с другими. но тебе это вообще не надо, должно быть обычное json тело с подходящий под него заголовок Content-Type, который укажет, что это json в ответе (почитай о том, что такое Content-Type в запросах и овтетах и вообще какие заголовки бывают и что для чего пирменяется , что означает). можешь открыть нанель разработчика в браузере F12 и во вкладке сеть посмотреть на заголовки, котрые отправляет и принимает твой бразуер при работе с любыми страницами

2024-03-02 19:10 UTC, ribatulin commented on internal/services/handler.go
> +	if h.s.RulesLen() == 0 {
отсутствие правил - не ошибка, простор операция ни в одном счетчике не зарегистрируется по итогу

2024-03-02 19:16 UTC, ribatulin commented on internal/services/handler.go
> +		if h.s.IsCounter(keyCounter) {
тут видно, что лишняя вложенность возникла и от того код усложнился. разбить на два этапа
1) получаем счетчик

```
if h.s.IsCounter(keyCounter) {
			_, tmpCounter := h.s.Counter(keyCounter)
			c := tmpCounter.(counter)
} else {
    aNewCounter := newCounter()
}
```
2) увеличиваем полученный счетчик в зависимости от типа правила
```
if aRule.AggregateValue == count {
....++
} else {
c.Value += int(mapping[amount].(float64))
}
````
и без вложенности уже друг в друга этих двух независимых блоков

2024-03-02 19:18 UTC, ribatulin commented on internal/services/handler.go
> +				h.s.SetCounter(keyCounter, c)
счетчик уже есть и только что достан из Storage, зачем второй раз его через Set туда добавлять? если это другой объект, то что стало с предыдущим?

2024-03-02 19:29 UTC, ribatulin commented on internal/hashStorage/storage.go
> +	s.archivist[idRule] = idCounter
явный баг. тут написано так, что у одного правила возможен только один счетчик. 
хотя одно правило "сколько платил клиент " может принять хоть 100 клиентов, будет 100 счетчиков привязанных к правилу. 

То, что нужен отдельный метод, который как то связывает правила и счетчики, уже признак плохого кода, в хорошем коде нельзя было бы создать счетчик , не привязанный к правилу. 

Пиши такой код, будто им будет пользоваться балбес, которому нельзя зать ошибиться. То, что для связи счетчиков и правил нужен отдельный метод - дает поле для распростанения ошибок, ведь его модно просто забыть вызвать. Почитай обязательно! про принцип Poka-Yoke и следуй ему в коде и проектировании АПИ и классов.  всегда думай, что код, который ты пишешь, будут использовать другие разработчики и нельзя дать им засунуть кубик в треугольное отверстие, а шарик в прямоугольное. Принцип Poka Yoke запомни, и не давай людям возможность совершить ненужную ошибку  при работе с твоим кодом . и ты сам один из этих людей :)

2024-03-03 05:06 UTC, 1Kabman1 commented on .gitignore
> +.idea/workspace.xml
принля , исправлено

2024-03-03 06:01 UTC, 1Kabman1 commented on .gitignore
> +go.mod
gitignor исправил координально


# Intellij project files Ж :l это файлы которые ипользует разные IDE
*.ipr
*.iws
.idea/
api/.idea/


# go.gitignore from https://github.com/github/gitignore/blob/master/Go.gitignore
# Binaries for programs and plugins : Двоичные файлы для программ и плагинов
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it) : Если ты исполюзешь vendor что это чначитю Go vendor это команда для сборки всех зависимостей прямо на компе в папке vendor. если ты не собираешь все зависимости на компе go автоматически подтягивает все нужное из нета .
# If you use Go Vendor to build code
# go.mod
# go.sum
# vendor/

2024-03-03 06:05 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +		archivist: make(map[int]int),
Это архивист видущий соотношение платежей к правилам , записывает  по id  
id правила = массив id платежей , только вот тут баг

2024-03-03 06:27 UTC, 1Kabman1 commented on .gitignore
> +go.mod
Посмотрел по примерам , практически никто не отсавляет данные файлы , зависимости подтягиваются самми

2024-03-03 07:03 UTC, 1Kabman1 commented on .gitignore
> +go.mod
# Intellij project files
*.iml
*.ipr
*.iws
.idea/
api/.idea/


# go.gitignore from https://github.com/github/gitignore/blob/master/Go.gitignore
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# If you use Go Vendor to build code
# go.mod
# go.sum
# vendor/
Нашел в инете все предельно понятно ))
 vendor это команда есть такая go  vendor  создает паку  vendor и собирает все зависимости непосредственно в директории приложения

2024-03-03 07:03 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +		archivist: make(map[int]int),
исправил , а так же добавил тестирование на проверку

2024-03-03 07:50 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +		archivist: make(map[int]int),
так же называется архивариус , завписывает отношение между правилами и счетчиками. У каждого правила может быть множество счетчиков. Только тут баг )) Исправил на map[int][]int где ключь это айди правила а значение это айди счетчика (айди уникальные )

2024-03-03 08:16 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +func (s *Storage) IsRule(key string) bool {
Изменил название с IsRule  fна HasRule , а также IsCounter на   HasCounter

2024-03-03 08:18 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +func (s *Storage) IsCounter(key [16]byte) bool {
+

2024-03-03 08:18 UTC, 1Kabman1 commented on internal/services/handler.go
> +	if h.s.RulesLen() == 0 {
пирнял , исправил возвращаю пустой массив

2024-03-03 10:12 UTC, 1Kabman1 commented on internal/services/handler.go
> +		w.Header().Set("Message", "rule already exists")
Исправил , но в go имеется оссобенность : 
HTTP заголовки по умолчанию от веб-сервера
При отправке ответа, Go автоматически установит для вас три сгенерированных системой HTTP заголовка: Date, Content-Length и Content-Type.

Заголовок Content-Type (тип контента) весьма интересен. Go попытается автоматически узнать тип контента проанализировав содержимое тела ответа с помощью функции http.DetectContentType(). Если эта функция не сможет определить тип контента, Go укажет следующее значение для заголовка Content-Type: application/octet-stream.

Функция http.DetectContentType() обычно работает довольно неплохо. Однако главная проблема веб-разработчиков, плохо знакомыми с Go, заключается в том, что данная функция не может отличить [JSON](https://golangs.org/json) от обычного текста. По умолчанию, ответы содержащие JSON будут отправляться с заголовком Content-Type: text/plain; charset=utf-8. Вы можете предотвратить это, установив правильный заголовок вручную следующим образом: w.Header().Set("Content-Type", "application/json")

2024-03-03 10:36 UTC, 1Kabman1 commented on internal/services/handler.go
> +		if h.s.IsCounter(keyCounter) {
Реализовал дополнитетельные вспамогательные функции increaseTheCounter и addTheCounter

2024-03-03 10:46 UTC, 1Kabman1 commented on internal/services/handler.go
> +				h.s.SetCounter(keyCounter, c)
Честно не понял вопрос

2024-03-03 10:46 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +	s.archivist[idRule] = idCounter
Баг исправил

2024-03-03 19:19 UTC, ribatulin commented on internal/hashStorage/storage.go
> +func (s *Storage) SetCounter(key [16]byte, nameRule string) {
там где вызывается SetCounter у тебя есть полный объект правила. при этов ты передаешь в SetCuonter Name правила как аргумент, чтобы потом по нему получить id . А зачем это надо, почему просто сразу id правила не передать вместо Name?

2024-03-04 20:53 UTC, 1Kabman1 commented on internal/hashStorage/storege_test.go
> +package hashStorage
Спасибо)

2024-03-04 20:57 UTC, 1Kabman1 commented on internal/services/handler.go
> +	if h.s.RulesLen() == 0 {
Исправлено

2024-03-04 21:00 UTC, 1Kabman1 commented on internal/services/handler.go
> +				h.s.SetCounter(keyCounter, c)
Исправил за счет привязки  серилизации и десерелизации к конкртным    типам  rule , counter  , ушел от interface{}

2024-03-04 21:02 UTC, 1Kabman1 commented on internal/hashStorage/storage.go
> +func (s *Storage) SetCounter(key [16]byte, nameRule string) {
Так и сделал , 
`func (s *Storage) SetCounter(key [16]byte, idRule int) {
	aNewCounter := NewCounter()
	idCounter := s.CounterLen() + 1
	aNewCounter.id = idCounter
	s.counter[key] = &aNewCounter
	s.AddToArchivist(idRule, idCounter)
}`

2024-03-04 21:03 UTC, 1Kabman1 commented
Так же сделал небольшой рефакторинг , код стал более читабельным и компактнее

2024-03-04 22:19 UTC, ribatulin approved these changes
вроде все ок. Готов принять и потестить

2024-03-05 10:03 UTC, merged